// Code generated by INKWASM BUILD; DO NOT EDIT
#include "textflag.h"

TEXT ·getBasicDecoder(SB), NOSPLIT, $0
	JMP ·_getBasicDecoder(SB)
	RET

TEXT ·getSliceDecoder(SB), NOSPLIT, $0
	JMP ·_getSliceDecoder(SB)
	RET

TEXT ·newObjectFromSyscall(SB), NOSPLIT, $0
	JMP ·_newObjectFromSyscall(SB)
	RET

TEXT ·getNull(SB), NOSPLIT, $0
	JMP ·_getNull(SB)
	RET

TEXT ·getUndefined(SB), NOSPLIT, $0
	JMP ·_getUndefined(SB)
	RET

TEXT ·getGlobal(SB), NOSPLIT, $0
	JMP ·_getGlobal(SB)
	RET

TEXT ·makeObj(SB), NOSPLIT, $0
	JMP ·_makeObj(SB)
	RET

TEXT ·free(SB), NOSPLIT, $0
	JMP ·_free(SB)
	RET

TEXT ·call(SB), NOSPLIT, $0
	JMP ·_call(SB)
	RET

TEXT ·callVoid(SB), NOSPLIT, $0
	JMP ·_callVoid(SB)
	RET

TEXT ·invoke(SB), NOSPLIT, $0
	JMP ·_invoke(SB)
	RET

TEXT ·invokeVoid(SB), NOSPLIT, $0
	JMP ·_invokeVoid(SB)
	RET

TEXT ·newObj(SB), NOSPLIT, $0
	JMP ·_newObj(SB)
	RET

TEXT ·getIndex(SB), NOSPLIT, $0
	JMP ·_getIndex(SB)
	RET

TEXT ·getProp(SB), NOSPLIT, $0
	JMP ·_getProp(SB)
	RET

TEXT ·setProp(SB), NOSPLIT, $0
	JMP ·_setProp(SB)
	RET

TEXT ·setPropObj(SB), NOSPLIT, $0
	JMP ·_setPropObj(SB)
	RET

TEXT ·encodeString(SB), NOSPLIT, $0
	JMP ·_encodeString(SB)
	RET

TEXT ·copyBytes(SB), NOSPLIT, $0
	JMP ·_copyBytes(SB)
	RET

TEXT ·instanceOf(SB), NOSPLIT, $0
	JMP ·_instanceOf(SB)
	RET

TEXT ·equal(SB), NOSPLIT, $0
	JMP ·_equal(SB)
	RET

TEXT ·strictEqual(SB), NOSPLIT, $0
	JMP ·_strictEqual(SB)
	RET
