// Code generated by INKWASM BUILD; DO NOT EDIT
#include "textflag.h"

TEXT ·__getBasicDecoder(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·getBasicDecoder(SB), NOSPLIT, $0
	JMP ·_getBasicDecoder(SB)
	RET

TEXT ·__getSliceDecoder(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·getSliceDecoder(SB), NOSPLIT, $0
	JMP ·_getSliceDecoder(SB)
	RET

TEXT ·__newObjectFromSyscall(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·newObjectFromSyscall(SB), NOSPLIT, $0
	JMP ·_newObjectFromSyscall(SB)
	RET

TEXT ·__getNull(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·getNull(SB), NOSPLIT, $0
	JMP ·_getNull(SB)
	RET

TEXT ·__getUndefined(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·getUndefined(SB), NOSPLIT, $0
	JMP ·_getUndefined(SB)
	RET

TEXT ·__getGlobal(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·getGlobal(SB), NOSPLIT, $0
	JMP ·_getGlobal(SB)
	RET

TEXT ·__makeObj(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·makeObj(SB), NOSPLIT, $0
	JMP ·_makeObj(SB)
	RET

TEXT ·__free(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·free(SB), NOSPLIT, $0
	JMP ·_free(SB)
	RET

TEXT ·__call(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·call(SB), NOSPLIT, $0
	JMP ·_call(SB)
	RET

TEXT ·__callVoid(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·callVoid(SB), NOSPLIT, $0
	JMP ·_callVoid(SB)
	RET

TEXT ·__invoke(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·invoke(SB), NOSPLIT, $0
	JMP ·_invoke(SB)
	RET

TEXT ·__invokeVoid(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·invokeVoid(SB), NOSPLIT, $0
	JMP ·_invokeVoid(SB)
	RET

TEXT ·__newObj(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·newObj(SB), NOSPLIT, $0
	JMP ·_newObj(SB)
	RET

TEXT ·__getIndex(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·getIndex(SB), NOSPLIT, $0
	JMP ·_getIndex(SB)
	RET

TEXT ·__getProp(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·getProp(SB), NOSPLIT, $0
	JMP ·_getProp(SB)
	RET

TEXT ·__setProp(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·setProp(SB), NOSPLIT, $0
	JMP ·_setProp(SB)
	RET

TEXT ·__encodeString(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·encodeString(SB), NOSPLIT, $0
	JMP ·_encodeString(SB)
	RET

TEXT ·__copyBytes(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·copyBytes(SB), NOSPLIT, $0
	JMP ·_copyBytes(SB)
	RET

TEXT ·__instanceOf(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·instanceOf(SB), NOSPLIT, $0
	JMP ·_instanceOf(SB)
	RET

TEXT ·__equal(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·equal(SB), NOSPLIT, $0
	JMP ·_equal(SB)
	RET

TEXT ·__strictEqual(SB), NOSPLIT, $0
	CallImport
	RET

TEXT ·strictEqual(SB), NOSPLIT, $0
	JMP ·_strictEqual(SB)
	RET
