// Code generated by INKWASM BUILD; DO NOT EDIT
(() => {
	if (globalThis.inkwasm === undefined) {
		globalThis.inkwasm = {Load: {}};
	}

})();
// Code generated by INKWASM BUILD; DO NOT EDIT
(() => {
	Object.assign(go.importObject.gojs, {

		"github.com/inkeliz/go_inkwasm/inkwasm.__newObjectFromSyscall": (sp) => {
			let r = go._values[globalThis.inkwasm.Load.Uint32(go, sp, 8)]
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 16, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__getNull": (sp) => {
			let r = null
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 8, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__getUndefined": (sp) => {
			let r = undefined
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 8, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__getGlobal": (sp) => {
			let r = globalThis
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 8, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__makeObj": (sp) => {
			let r = globalThis.inkwasm.Internal.Make(globalThis.inkwasm.Load.Slice(go, sp, 8, globalThis.inkwasm.Load.ArrayInt32))
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 32, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__free": (sp) => {
			globalThis.inkwasm.Internal.Free(globalThis.inkwasm.Load.Int(go, sp, 8))

		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__call": (sp) => {
			try {
				let r = globalThis.inkwasm.Internal.Call(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.String(go, sp, 24),globalThis.inkwasm.Load.Slice(go, sp, 40, globalThis.inkwasm.Load.ArrayInterface))
				sp = go._inst.exports.getsp() >>> 0
				globalThis.inkwasm.Set.InkwasmObject(go, sp, 64, r)
				globalThis.inkwasm.Set.Bool(go, sp, 80, true)
						}catch(e){
				console.log(e)
				globalThis.inkwasm.Set.Bool(go, sp, 80, false)
			}
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__callVoid": (sp) => {
			try {
				let r = globalThis.inkwasm.Internal.Call(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.String(go, sp, 24),globalThis.inkwasm.Load.Slice(go, sp, 40, globalThis.inkwasm.Load.ArrayInterface))
				sp = go._inst.exports.getsp() >>> 0
				globalThis.inkwasm.Set.Bool(go, sp, 64, r)
				globalThis.inkwasm.Set.Bool(go, sp, 65, true)
						}catch(e){
				console.log(e)
				globalThis.inkwasm.Set.Bool(go, sp, 65, false)
			}
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__invoke": (sp) => {
			try {
				let r = globalThis.inkwasm.Internal.Invoke(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.Slice(go, sp, 24, globalThis.inkwasm.Load.ArrayInterface))
				sp = go._inst.exports.getsp() >>> 0
				globalThis.inkwasm.Set.InkwasmObject(go, sp, 48, r)
				globalThis.inkwasm.Set.Bool(go, sp, 64, true)
						}catch(e){
				console.log(e)
				globalThis.inkwasm.Set.Bool(go, sp, 64, false)
			}
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__invokeVoid": (sp) => {
			try {
				let r = globalThis.inkwasm.Internal.Invoke(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.Slice(go, sp, 24, globalThis.inkwasm.Load.ArrayInterface))
				sp = go._inst.exports.getsp() >>> 0
				globalThis.inkwasm.Set.Bool(go, sp, 48, r)
				globalThis.inkwasm.Set.Bool(go, sp, 49, true)
						}catch(e){
				console.log(e)
				globalThis.inkwasm.Set.Bool(go, sp, 49, false)
			}
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__newObj": (sp) => {
			try {
				let r = new globalThis.inkwasm.Load.InkwasmObject(go, sp, 8)(globalThis.inkwasm.Load.Slice(go, sp, 24, globalThis.inkwasm.Load.ArrayInterface))
				sp = go._inst.exports.getsp() >>> 0
				globalThis.inkwasm.Set.InkwasmObject(go, sp, 48, r)
				globalThis.inkwasm.Set.Bool(go, sp, 64, true)
						}catch(e){
				console.log(e)
				globalThis.inkwasm.Set.Bool(go, sp, 64, false)
			}
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__getIndex": (sp) => {
			let r = globalThis.inkwasm.Load.InkwasmObject(go, sp, 8)[globalThis.inkwasm.Load.Int(go, sp, 24)]
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 32, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__getProp": (sp) => {
			let r = globalThis.inkwasm.Load.InkwasmObject(go, sp, 8)[globalThis.inkwasm.Load.String(go, sp, 24)]
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 40, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__setProp": (sp) => {
			Reflect.set(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.String(go, sp, 24),globalThis.inkwasm.Load.String(go, sp, 40))

		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__setPropObj": (sp) => {
			Reflect.set(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.String(go, sp, 24),globalThis.inkwasm.Load.InkwasmObject(go, sp, 40))

		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__encodeString": (sp) => {
			let r = globalThis.inkwasm.Internal.EncodeString(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8))
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 24, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__copyBytes": (sp) => {
			globalThis.inkwasm.Internal.Copy(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.Slice(go, sp, 24, globalThis.inkwasm.Load.ArrayByte))

		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__instanceOf": (sp) => {
			let r = globalThis.inkwasm.Internal.InstanceOf(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.InkwasmObject(go, sp, 24))
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.Bool(go, sp, 40, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__equal": (sp) => {
			let r = globalThis.inkwasm.Internal.Equal(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.InkwasmObject(go, sp, 24))
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.Bool(go, sp, 40, r)
		},

		"github.com/inkeliz/go_inkwasm/inkwasm.__strictEqual": (sp) => {
			let r = globalThis.inkwasm.Internal.StrictEqual(globalThis.inkwasm.Load.InkwasmObject(go, sp, 8),globalThis.inkwasm.Load.InkwasmObject(go, sp, 24))
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.Bool(go, sp, 40, r)
		},

	})
})();
