// Code generated by INKWASM BUILD; DO NOT EDIT

package inkwasm

import (
	"runtime"
)

func _getBasicDecoder(s string) (_ Object) {
	r0 := __getBasicDecoder(s)
	runtime.KeepAlive(s)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__getBasicDecoder
func __getBasicDecoder(s string) (_ Object)

func _getSliceDecoder(f Object) (_ Object) {
	r0 := __getSliceDecoder(f)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__getSliceDecoder
func __getSliceDecoder(f Object) (_ Object)

func _newObjectFromSyscall(i uint32) (_ Object) {
	r0 := __newObjectFromSyscall(i)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__newObjectFromSyscall
func __newObjectFromSyscall(i uint32) (_ Object)

func _getNull() (_ Object) {
	r0 := __getNull()

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__getNull
func __getNull() (_ Object)

func _getUndefined() (_ Object) {
	r0 := __getUndefined()

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__getUndefined
func __getUndefined() (_ Object)

func _getGlobal() (_ Object) {
	r0 := __getGlobal()

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__getGlobal
func __getGlobal() (_ Object)

func _makeObj(p0 []int32) (_ Object) {
	r0 := __makeObj(p0)
	runtime.KeepAlive(p0)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__makeObj
func __makeObj(p0 []int32) (_ Object)

func _free(ref int) {
	__free(ref)

}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__free
func __free(ref int)

func _call(o Object, k string, args []int32) (_ Object, _ bool) {
	r0, r1 := __call(o, k, args)
	runtime.KeepAlive(k)
	runtime.KeepAlive(args)

	return r0, r1
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__call
func __call(o Object, k string, args []int32) (_ Object, _ bool)

func _callVoid(o Object, k string, args []int32) (_ bool, ok bool) {
	r0, r1 := __callVoid(o, k, args)
	runtime.KeepAlive(k)
	runtime.KeepAlive(args)

	return r0, r1
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__callVoid
func __callVoid(o Object, k string, args []int32) (_ bool, ok bool)

func _invoke(o Object, args []int32) (_ Object, _ bool) {
	r0, r1 := __invoke(o, args)
	runtime.KeepAlive(args)

	return r0, r1
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__invoke
func __invoke(o Object, args []int32) (_ Object, _ bool)

func _invokeVoid(o Object, args []int32) (_ bool, ok bool) {
	r0, r1 := __invokeVoid(o, args)
	runtime.KeepAlive(args)

	return r0, r1
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__invokeVoid
func __invokeVoid(o Object, args []int32) (_ bool, ok bool)

func _newObj(o Object, args []int32) (_ Object, _ bool) {
	r0, r1 := __newObj(o, args)
	runtime.KeepAlive(args)

	return r0, r1
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__newObj
func __newObj(o Object, args []int32) (_ Object, _ bool)

func _getIndex(o Object, i int) (_ Object) {
	r0 := __getIndex(o, i)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__getIndex
func __getIndex(o Object, i int) (_ Object)

func _getProp(o Object, k string) (_ Object) {
	r0 := __getProp(o, k)
	runtime.KeepAlive(k)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__getProp
func __getProp(o Object, k string) (_ Object)

func _setProp(o Object, k string, v string) {
	__setProp(o, k, v)
	runtime.KeepAlive(k)
	runtime.KeepAlive(v)

}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__setProp
func __setProp(o Object, k string, v string)

func _setPropObj(o Object, k string, v Object) {
	__setPropObj(o, k, v)
	runtime.KeepAlive(k)

}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__setPropObj
func __setPropObj(o Object, k string, v Object)

func _encodeString(o Object) (_ Object) {
	r0 := __encodeString(o)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__encodeString
func __encodeString(o Object) (_ Object)

func _copyBytes(o Object, buf []byte) {
	__copyBytes(o, buf)
	runtime.KeepAlive(buf)

}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__copyBytes
func __copyBytes(o Object, buf []byte)

func _instanceOf(o Object, v Object) (_ bool) {
	r0 := __instanceOf(o, v)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__instanceOf
func __instanceOf(o Object, v Object) (_ bool)

func _equal(o Object, v Object) (_ bool) {
	r0 := __equal(o, v)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__equal
func __equal(o Object, v Object) (_ bool)

func _strictEqual(o Object, v Object) (_ bool) {
	r0 := __strictEqual(o, v)

	return r0
}

//go:wasmimport gojs github.com/inkeliz/go_inkwasm/inkwasm.__strictEqual
func __strictEqual(o Object, v Object) (_ bool)
